fix: reset screen brightness after exiting QR code using back button
DanXi-Dev/DanXi pull request #259
Opened 2023-07-25 01:53 UTC by kooWZ

2023-07-25 08:23 UTC, w568w commented
事实上，一个更好的办法需要先了解 `show……Dialog()` 系列的工作模式：

https://github.com/DanXi-Dev/DanXi/blob/b757bedf66b8ff2f4cf5422c4b644c2fa00dd6a3/lib/widget/dialogs/qr_code_dialog.dart#L40-L44


`await showPlatformDialog<T>` 将会阻塞，直到窗口关闭：

1. 返回 `T obj` 对象：如果使用 `Navigator.pop(context, obj)` 且 `obj != null`；
2. 返回 `null`：如果使用 `Navigator.pop(context)` 或用动作关闭对话框（无论以何种方式，如按返回、在 `barrierDismissible = true` 时触摸框外）

因此，合理的做法是在这里 `await` 一下 `showPlatformDialog`，然后重置亮度设置。

2023-07-25 08:24 UTC, w568w requested changes
如上。

2023-07-25 08:25 UTC, singularity-s0 requested changes
`WillPopScope`在iOS上会导致返回手势失效，请采用其他办法实现。

2023-07-25 08:28 UTC, w568w commented
> `WillPopScope`在iOS上会导致返回手势失效，请采用其他办法实现。

只是好奇，但是加在对话框中也会失效吗？

2023-07-25 08:32 UTC, singularity-s0 commented
> > `WillPopScope`在iOS上会导致返回手势失效，请采用其他办法实现。
> 
> 只是好奇，但是加在对话框中也会失效吗？

那应该不会，对话框中不适用返回手势

2023-07-25 15:37 UTC, singularity-s0 approved these changes

2023-07-26 13:43 UTC, w568w approved these changes
LGTM

2023-07-26 13:43 UTC, merged