首次使用「日程」页面时，提供功能展示
DanXi-Dev/DanXi pull request #275
Opened 2023-08-05 12:58 UTC by cryindevil

实现首次使用「日程」页面时，提供功能展示
注：是旦夕app下载后第一次切换到日程页面时才会打开，要再次看到只有卸载重新下载才会看到。
在开发过程中往本地仓库提交了两次，用的提交备注显得很意义不明，下一次会注意的。
（提交当中有几处无意义的改动我估计是vsode自动的格式调整，应该没事吧？）

2023-08-05 16:15 UTC, w568w requested changes
如上，建议逐一核实和修改。

2023-08-05 16:15 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "start_date_select": "Term start date query",
建议统一用 Semester，项目翻译中基本没有用过 Term 这一单词。

2023-08-05 16:15 UTC, w568w commented on lib/l10n/intl_ja.arb
如果全为机翻的话，建议是不如不添加日语。翻译总可以之后补上的。

2023-08-05 16:15 UTC, w568w commented on lib/page/subpage_timetable.dart
> +      Future.delayed(Duration.zero, showTutorial);
要延迟到下一帧显示，应该使用 [`WidgetsBinding.instance.addPostFrameCallback`](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)。`Future.delayed(Duration.zero)` 虽然也会推迟到下一次 Event 循环开始时进行，但语义没有前者清晰。

2023-08-05 16:15 UTC, w568w commented on lib/page/subpage_timetable.dart
> +  late TutorialCoachMark tutorialCoachMark;
因为 `tutorialCoachMark` 本身只在 `initState` 里用到，这里应该无需作为一个类的字段存储。

2023-08-05 16:15 UTC, w568w commented on lib/page/subpage_timetable.dart
> +    );
这里为什么要把同一段话复制粘贴三遍？

2023-08-05 16:15 UTC, w568w commented on lib/provider/settings_provider.dart
> +  bool get hasVistedTimeTable {
`Visited` 拼写错误。

2023-08-05 16:15 UTC, w568w commented on pubspec.lock
不要推送含有镜像源 `flutter-io.cn` 的 `pubspec.lock` 上去。参考这里的「警告」段落：<https://danxi.fduhole.com/docs/docs/danxi/publish/android-windows#f-droid>

（平时提交更改时，不一定要按上面文档里说的「暂时修改你的镜像设置」来做，直接不提交本文件即可。当然最好的办法是「修改你的镜像设置」，然后配好系统代理，一劳永逸）

2023-08-06 03:23 UTC, cryindevil commented on flutter_02.png
这两张图片可能web版自动生成的，已从提交中移除

2023-08-06 03:35 UTC, cryindevil commented
>如果全为机翻的话，建议是不如不添加日语。

已设置为英语
>建议统一用 Semester。

已改
>要延迟到下一帧显示，应该使用 [WidgetsBinding.instance.addPostFrameCallback]

最初我的想法是给用户一定时间看一下，但我后来觉得意义不大就设置成0，现在我设置为直接调用showTutorial()

>因为 tutorialCoachMark 本身只在 initState 里用到，这里应该无需作为一个类的字段存储。

tutorialCoachMark 并非只在initState里用到，initstate中只是调用了createTutorial()和showTutorial()而这两个函数体中依赖于tutorialCoachMark （这两个函数于initstate是同一级定义的）
>Visited 拼写错误。

已改
>不要推送含有镜像源 flutter-io.cn 的 pubspec.lock 上去

已改，我复制粘贴了旦夕仓库中pubspec.lock内容提交了进去

2023-08-06 04:00 UTC, w568w commented
不用一一回复，更好的做法是 Resolve 掉对应的 Conversation。

2023-08-06 04:05 UTC, w568w requested changes

2023-08-06 04:05 UTC, w568w commented on lib/l10n/intl_ja.arb
> +  "start_date_select_message": "You must select the start date of the semester to view your class schedule. Not selecting will result in a date error. \nTip: Start date is the Monday of the first wee
这部分直接不写即可。没有规定说每个 key 一定要在所有语言文件里都出现，不需要用其他语言占位，建议直接删去。

2023-08-06 04:05 UTC, w568w commented on lib/page/subpage_timetable.dart
> +      showTutorial();
测试过这样能正常运行吗？`initState` 时似乎不允许立刻显示新的界面。

2023-08-06 04:06 UTC, w568w commented on lib/page/subpage_timetable.dart
> +    );
这个怎么就 resolve 了？

2023-08-06 04:06 UTC, w568w commented on lib/page/subpage_timetable.dart
> +  late TutorialCoachMark tutorialCoachMark;
这个怎么就 resolve 了？

2023-08-06 04:09 UTC, cryindevil commented on lib/page/subpage_timetable.dart
> +      showTutorial();
测试过，没问题

2023-08-06 07:16 UTC, w568w requested changes
这里也可以改一下。

2023-08-06 07:16 UTC, w568w commented on lib/page/subpage_timetable.dart
> +    if (SettingsProvider.getInstance().hasVisitedTimeTable == false) {
不需要用 `== false`，见 https://github.com/DanXi-Dev/DanXi/pull/262/files/991fa74065e4e212039bdba2577f9b2aaf9306ed#diff-8113dade2c0ca0091ae24cd29d0293d3f2dba81275d6c0f75b7e1c0d30348f36R692 。

2023-08-07 11:35 UTC, w568w approved these changes
LGTM

2023-08-07 11:36 UTC, merged