feat: fold long content in search results
DanXi-Dev/DanXi pull request #286
Opened 2023-08-18 12:37 UTC by kooWZ

目前的设计是展示关键词及前后各15个字

由于后端搜索时会做分词，分词后得到的搜索结果不含有完整的关键词，`fullContent.indexOf(searchKeyWord!)`会失败，返回-1，此时展示开头的一小段文字
暂时没有想到更好的解决办法

效果图![_-1000191933__6756a412fdd44c1bcb585f215698326f_-877532528_Screenshot_20230818_203305_0_xg_0](https://github.com/DanXi-Dev/DanXi/assets/60533182/c11bd84b-4e42-4829-96a9-5ca4b40c19dc)
Closes #249

2023-08-18 13:31 UTC, w568w requested changes

2023-08-18 13:31 UTC, w568w commented on lib/widget/opentreehole/treehole_widgets.dart
> +        child: (foldLongFloor == true ||
依然，这里不需要 `== true`，一方面是确实是不需要（另外两个都是 `bool?`），一方面是和 397 行保持一致。

2023-08-18 15:16 UTC, kooWZ commented on lib/widget/opentreehole/treehole_widgets.dart
> +      int endIndex = keywordIndex + searchKeyWord!.length + showCharCount;
理想的效果是显示关键词前后各一小段文本，那么依然需要用类似`startIndex=keyWordIndex-const`·的方法指定起始位置吧？
否则`renderText(floor.content!,xxx)`会从开头开始显示
或者有什么办法能让关键词自动居中？

2023-08-19 01:46 UTC, w568w commented on lib/widget/opentreehole/treehole_widgets.dart
> +      int endIndex = keywordIndex + searchKeyWord!.length + showCharCount;
> 依然需要用类似 `startIndex=keyWordIndex-const` 的方法指定起始位置吧？

是的。这就是为什么我只说「下面的 `substring` 的 **`endIndex`** 可以删去」……

2023-08-19 11:49 UTC, w568w commented on lib/widget/opentreehole/treehole_widgets.dart
> +        subContent = "...${fullContent.substring(startIndex, endIndex)}...";
哦……我使用了错误的字符，已更正。

2023-08-19 11:57 UTC, w568w approved these changes

2023-08-19 11:57 UTC, merged