many fixes
DanXi-Dev/DanXi pull request #291
Opened 2023-09-19 09:44 UTC by kooWZ

Closes #284

2023-09-19 09:48 UTC, w568w commented
Seems a large PR! 👍 I will review it as soon as I have some time.

2023-09-23 09:13 UTC, w568w requested changes

2023-09-23 09:13 UTC, w568w commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
This dialog may pop up **every time** you select a school building or refresh the page.

For a less-intrusive notice, check out:

https://github.com/DanXi-Dev/DanXi/blob/a601dba7f268b0b84bf005ddc9df7c07d2d7d4d0/lib/page/dashboard/exam_detail.dart#L281-L291

This function builds a red-colored card at the top of page, to notify the user that the information could be inaccurate.

2023-09-23 09:13 UTC, w568w commented on lib/repository/fdu/empty_classroom_repository.dart
> +          String? buildingName, DateTime? date) async =>
In fact you do not need an `async` keyword here, since `UISLoginTool.tryAsyncWithAuth` returns a `Future`. Let's prevent unnecessary changes…

2023-09-23 09:14 UTC, w568w commented
Most look good to me and some bug-fixes are impressive. Good PR :+1:

2023-09-23 11:42 UTC, kooWZ commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
I can't think of a good solution.
If we use a boolean to decide whether to show the alert and call `setState` after checking connection, the widget containing classroom information will also be reloaded.
All I can think of is wrapping everything in a big `FutureWidget` , but that seems strange.

2023-09-23 11:58 UTC, kooWZ commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
..Or use another `FutureWidget` like this:
```dart
              FutureWidget<bool>(
                future:
                    EmptyClassroomRepository.getInstance().checkConnection(),
                successBuilder: (BuildContext context,
                        AsyncSnapshot<dynamic> snapshot) =>
                    snapshot.data!
                        ? Container()
                        : Card(
                        color: Theme.of(context).colorScheme.error,
                        child: ListTile(
                          visualDensity: VisualDensity.comfortable,
                          title: Text(
                            S.of(context).limited_mode_title,
                            style: const TextStyle(color: Colors.white),
                          ),
                          subtitle: Text(
                              S.of(context).empty_classroom_warning,
                              style: const TextStyle(color: Colors.white)),
                        )),
                errorBuilder: Container(),
                loadingBuilder: Container(),
              ),
```
In this case we will have to send an extra network request

2023-09-24 02:13 UTC, w568w commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
> I can't think of a good solution.

IMMO the solution is quite simple: `getRoomInfo` knows which source it is using and `successBuilder` needs it; so make `getRoomInfo` also return the source.

You can use either [`Pair`](https://github.com/DanXi-Dev/DanXi/blob/main/lib/model/pair.dart) or [`Records`](https://dart.dev/language/records) to achieve this.

2023-09-24 03:05 UTC, kooWZ commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
But the alert should be shown on the top of the page, which is not inside the `FutureWidget`.
So I said *wrapping everything in a big `FutureWidget`*, but it seems strange

2023-09-26 15:17 UTC, kooWZ commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
Maybe take a look at commit [05fd513](https://github.com/DanXi-Dev/DanXi/pull/291/commits/05fd51326766fdff8261ba6613afdf4f808e4996) to see if it's an ideal approach?

2023-09-27 03:29 UTC, w568w commented on lib/page/dashboard/empty_classroom_detail.dart
> +                ));
> Maybe take a look at commit [05fd513](https://github.com/DanXi-Dev/DanXi/pull/291/commits/05fd51326766fdff8261ba6613afdf4f808e4996) to see if it's an ideal approach?

LGTM. Will test it later.

2023-09-28 11:19 UTC, w568w approved these changes
Wonderful! :fireworks:

2023-09-28 11:19 UTC, ivanfei-1 commented
🧇

2023-09-28 11:19 UTC, merged