feat: _BASE_URL (for opentreehole), _BASE_AUTH_URL and _IMAGE_BASE_URL are now modifiable
DanXi-Dev/DanXi pull request #294
Opened 2023-09-26 04:06 UTC by ivanfei-1

close #260.

2023-09-26 07:18 UTC, w568w requested changes

2023-09-26 07:18 UTC, w568w commented on lib/provider/settings_provider.dart
> +  static const String KEY_IMAGE_BASE_URL = "https://image.fduhole.com";
Do not use a site URL as the key. Follow the naming style of other keys (i.e. `lower_snake_case`).

2023-09-26 07:18 UTC, w568w commented on lib/provider/settings_provider.dart
> +      return "https://www.fduhole.com/api";
Do not hard-code the base URLs everywhere. AFAICS, they are at least coded again and again, in:

1. `lib/page/settings/diagnostic_console.dart` (3x)
2. `lib/provider/settings_provider.dart` (6x)

You should either define the default value **only** in `constants.dart`, or **only** in `get XXX {}` methods here.

2023-09-26 07:18 UTC, w568w commented on lib/provider/settings_provider.dart
> +      preferences!.setString(KEY_BASE_URL, "https://www.fduhole.com/api");
Why set the url to its default value when someone calls `SettingsProvider.baseUrl = null`? 

IMMO this `set` should not accept a nullable parameter at all, i.e. 

```
set baseUrl(String value) {
// ...
}
```

2023-09-27 11:45 UTC, w568w approved these changes
Almost great to me. Just a subtle change required.

2023-09-27 11:45 UTC, w568w commented on lib/common/constant.dart
> +  /// The default urls of the OpenTreeHoleRepository
It is recommended to follow the documentation syntax to highlight the names of classes and objects with `[]`, e.g.

```
The default URLs of [OpenTreeHoleRepository].
```

In IDEs (like Intellij IDEA), you can jump to `OpenTreeHoleRepository`'s definition by clicking on `[OpenTreeHoleRepository]` with `Command` pressed.

2023-09-27 16:50 UTC, ivanfei-1 commented on lib/common/constant.dart
> +  /// The default urls of the OpenTreeHoleRepository
All done.

2023-09-28 10:49 UTC, merged