New admin punishment page
DanXi-Dev/DanXi pull request #303
Opened 2023-10-18 15:01 UTC by HydrogenC

WIP, shall close #261.

2023-10-20 13:52 UTC, w568w commented
Being very busy these days, and as soon as I have time I'll start reviewing the parts of it that have something to do with the admin page.

Are there any more commits unrelated to the admin page (i.e. about tweaking the UI layout)? I'll cherry-pick them.

2023-10-20 14:42 UTC, HydrogenC commented
I believe `074ace9`, `a8a27f6`, `3ec1fb5` are fixes that have nothing to do with the admin page.

2023-12-01 12:31 UTC, HydrogenC commented
Is this PR superseded by #318 already?

2023-12-06 00:59 UTC, HydrogenC commented
I accidentally did the same thing. I gotta have `f80a9cb` reverted.

2024-03-05 07:14 UTC, w568w commented
Has it been already done, or still working in progress?

2024-03-05 09:31 UTC, HydrogenC commented
> Sorry for too late reply. Has it been already done, or still working in progress?

Feature complete already. But I haven't done any code style-checking yet. I will do that asap.

2024-03-07 03:18 UTC, w568w commented
> Tested to work on PC, but not tested on mobile platforms yet (help wanted). Since this PR replaces the old solution, it has to be well-tested (however testing is not possible now since the server is down).

That's fine. I may merge this after the FDUHole server goes up again... As for now, I suggest keeping the PR open.

2024-03-29 14:17 UTC, w568w commented
I will test it on Android with the development server soon.

2024-03-30 03:49 UTC, w568w requested changes
Mostly LGTM. Except for a minor issue.

2024-03-30 03:49 UTC, w568w commented on lib/page/opentreehole/admin_operation.dart
> +          operation.reason.isEmpty ? "未知原因" : operation.reason);
You don't need to hard-code a default reason here: the backend has a default reason string when receiving an empty string, which is usually "违反社区规范". 

Anyway, this default string should be decided and maintained by the backend, not by us.

2024-03-30 12:26 UTC, w568w approved these changes

2024-03-30 12:27 UTC, merged