[Feature] Audit page
DanXi-Dev/DanXi pull request #318
Opened 2023-11-12 13:43 UTC by ivanfei-1

2023-11-12 15:26 UTC, w568w requested changes

2023-11-12 16:02 UTC, JingYiJun commented on lib/page/opentreehole/hole_reports.dart
> +    }).call(page);
这里的逻辑可能会导致第一页的数据加载两遍

2023-11-13 06:19 UTC, ivanfei-1 commented on lib/page/opentreehole/hole_reports.dart
> +import '../subpage_treehole.dart';
fixed in ea912a306c3fc2b047caed29c5ad72c1ef994b86

2023-11-13 07:34 UTC, w568w requested changes

2023-11-13 07:34 UTC, w568w commented on lib/page/opentreehole/hole_reports.dart
> +      TimeBasedLoadAdaptLayer(Constant.POST_COUNT_PER_PAGE, 1);
Two things to consider:

1. You use `Constant.POST_COUNT_PER_PAGE` to refer to the page size here, while using number `10` elsewhere. What if someday `Constant.POST_COUNT_PER_PAGE` is changed to, say, 11? Take care of the consistency;
2. The second argument is the **first page's index in the paging mechanism**. You should keep it same as what you set in the `PagedListView`:

```dart
child: PagedListView<OTAudit>(
  startPage: 0, // <- this number!
  pagedController: _auditListViewController,
```

2023-11-13 07:57 UTC, w568w requested changes

2023-11-13 07:57 UTC, w568w commented on lib/page/opentreehole/hole_reports.dart
> +      PagedListViewController();
Seems that you are using the same `_auditListViewController` for two different pages at the same time, which causes it controls only one of them according to the mounting order.

2023-11-13 09:01 UTC, ivanfei-1 commented on lib/page/opentreehole/hole_reports.dart
> +      TimeBasedLoadAdaptLayer(Constant.POST_COUNT_PER_PAGE, 1);
fixed in 71f601452fef515bd5de5893082defe4160d814e

2023-11-13 09:02 UTC, ivanfei-1 commented on lib/page/opentreehole/hole_reports.dart
> +      PagedListViewController();
Fixed in 71f601452fef515bd5de5893082defe4160d814e

2023-11-13 09:02 UTC, ivanfei-1 commented on lib/page/opentreehole/hole_reports.dart
> +    }).call(page);
Fixed.

2023-11-15 09:38 UTC, w568w approved these changes
Mostly LGTM. Some suggestions are listed below.

2023-11-15 09:38 UTC, w568w commented on ios/Runner.xcodeproj/project.pbxproj
@singularity-s0 Are these changes correct? They seemed to be dynamically determined before, but this PR hard-codes them now.

2023-11-15 09:38 UTC, w568w commented on lib/page/opentreehole/hole_reports.dart
> +          await refreshSelf();
Try removing this `refreshSelf()` to see whether it is unnecessary?

2023-11-15 09:38 UTC, w568w commented on lib/page/opentreehole/hole_reports.dart
> +        await refreshSelf();
Ditto.

2023-11-15 12:16 UTC, ivanfei-1 commented on lib/page/opentreehole/hole_reports.dart
> +          await refreshSelf();
Removed in 860fe62c308b3aa5c4bffe5e3d7bbea1c27b758c.

2023-11-15 12:16 UTC, ivanfei-1 commented on lib/page/opentreehole/hole_reports.dart
> +        await refreshSelf();
Removed in 860fe62c308b3aa5c4bffe5e3d7bbea1c27b758c.

2023-11-15 17:42 UTC, ivanfei-1 commented on ios/Runner.xcodeproj/project.pbxproj
Should be fixed in f35f726fda1627db97ade7c8267fe4c1e62eda43

2023-11-15 17:49 UTC, ivanfei-1 commented on ios/Runner.xcodeproj/project.pbxproj
Other changes are to ensure that Xcode can build the project and support for Vision Pro devices.
You can check them if you have time, otherwise these should be rather minor changes. @singularity-s0

2023-11-16 13:40 UTC, merged