Fix #326
DanXi-Dev/DanXi pull request #327
Opened 2024-01-01 15:14 UTC by w568w

As the title says.

See #326 for more details.

Fixes #326.

2024-01-02 09:28 UTC, HydrogenC requested changes
Thank you a lot for refractoring and removing those very old code that should have been deleted. It looks perfect now!

2024-01-02 09:28 UTC, HydrogenC commented on lib/page/danke/course_review_editor.dart
> +              SizedBox(width: 80, child: Text(widget.label)),
80 works better for Chinese, but I found that it isn't enough for Japanese or English, so I set it to 88. I believe the value should remain 88 before any better solution is found.

2024-01-02 09:52 UTC, w568w commented on lib/page/danke/course_review_editor.dart
> +              SizedBox(width: 80, child: Text(widget.label)),
> 80 ... isn't enough for Japanese or English, so set it to 88

OK, then I will revert it. 

`88px` caused an 8.2px layout overflow on my Android device, so I tuned it a bit. 

IMHO, the best solution is that a hard-coded dimension should not be used here. I think that you actually want to **align text labels and star selectors**, and `Column` + `Row` is not the solution. Please take a look at [flutter_layout_grid](https://pub.dev/packages/flutter_layout_grid).

2024-01-02 10:00 UTC, HydrogenC commented on lib/page/danke/course_review_editor.dart
> +              SizedBox(width: 80, child: Text(widget.label)),
It doesn't sound worth adding a new dependency for this tiny feature. I will try to implement this by myself with existing widget. It won't be too difficult, I guess.

2024-01-03 01:49 UTC, w568w commented on lib/page/danke/course_review_editor.dart
> +              SizedBox(width: 80, child: Text(widget.label)),
> It doesn't sound worth adding a new dependency for this tiny feature

So we already depend on [flutter_layout_grid](https://pub.dev/packages/flutter_layout_grid) for timetable layout.

> this doesn't actually solve the overflow under other languages

Yes. Check out our another dependency, [auto_size_text](https://pub.dev/packages/auto_size_text).

2024-01-03 01:53 UTC, w568w commented
After you approve it, we will merge it.

2024-01-03 06:05 UTC, HydrogenC approved these changes

2024-01-03 13:45 UTC, merged

2024-01-03 13:47 UTC, w568w commented
Now wait for #325 to merge. ;)