feat: Add faq guide afterq first login #269
DanXi-Dev/DanXi pull request #344
Opened 2024-04-03 02:23 UTC by cryindevil

2024-04-03 04:36 UTC, w568w requested changes

2024-04-03 04:36 UTC, w568w commented on lib/widget/dialogs/login_dialog.dart
> +          showFAQ();
Well, you are showing this after ***every***, not ***first*** login... Perhaps add a preference item to record this?

2024-04-03 04:36 UTC, w568w commented on lib/widget/dialogs/login_dialog.dart
> +    return showDialog<bool>(
Change to `showPlatformDialog`. 

[We never use `showDialog`](https://github.com/search?q=repo%3ADanXi-Dev%2FDanXi%20showDialog&type=code), since it always shows a Material-style dialog on all platforms.

2024-04-03 05:39 UTC, cryindevil commented on lib/widget/dialogs/login_dialog.dart
> +          showFAQ();
Unable to track first time of login in. Log out from the UIS account will wipe out local preferences.

2024-04-03 05:39 UTC, cryindevil commented on lib/widget/dialogs/login_dialog.dart
> +    return showDialog<bool>(
fixed

2024-04-03 07:40 UTC, w568w commented on lib/widget/dialogs/login_dialog.dart
> +    return showDialog<bool>(
> fixed

You needn't reply indeed. Use the `Resolve conversation` button below.

And when you feel the PR suitable for re-review, click `Re-request review` button beside the reviewer's avatar on the right column.

2024-04-03 07:42 UTC, w568w commented
And... `fix: ` prefix is usually abused for every single thing fixed. It should not be. 

Please take a look at an ad-hoc commit message guide here: https://github.com/DanXi-Dev/DanXi/commit/3262b64b61b8670c8879663df73ea1a140804ff5.

2024-04-09 06:07 UTC, w568w requested changes

2024-04-09 06:07 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "read":"read",
The `"read"` is used nowhere. Consider removing it.

2024-04-09 06:07 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "faq_url":"https://danxi-dev.feishu.cn/wiki/wikcnrPPGDCiTODBYRkdwLlHH65"
It'd better put URLs in `constant.dart`, not in translation strings. E.g.:

https://github.com/DanXi-Dev/DanXi/blob/3262b64b61b8670c8879663df73ea1a140804ff5/lib/common/constant.dart#L67-L72

2024-04-09 06:07 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "have_read":"have read",
"Have read" does not seem an appropriate word here. Maybe reuse `S.of(cxt).skip` or rephrase it to "I have read"?

2024-04-09 06:07 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "welcome_prompt":"If you are using DanXi for the first time, perhaps you would like to take a look at the FAQ section? \n\nWelcome to the DanXi!",
I suggest swapping two paragraphs, i.e.

```
Welcome to the DanXi!

If you are using DanXi for the first time, perhaps you would like to take a look at the FAQ section? 
```

2024-04-13 05:12 UTC, w568w approved these changes

2024-04-13 05:12 UTC, merged