[Feature] Quiz after registration
DanXi-Dev/DanXi pull request #345
Opened 2024-04-04 07:08 UTC by HydrogenC

Tested on windows and android already. However, further testing is still necessary, since I only tested it on my own account.

2024-04-04 07:14 UTC, HydrogenC commented
Resolves #239.

2024-04-04 15:36 UTC, w568w commented
Wow, really fast!



> Resolves #239.

You can use "fix" or "close" to link this PR to an issue.

E.g. Close #239.

2024-04-05 05:12 UTC, w568w requested changes

2024-04-05 05:12 UTC, w568w commented on lib/page/opentreehole/quiz.dart
> +                              });
Consider jump to the next question (unless there is no more question) on tapping?

2024-04-05 05:12 UTC, w568w commented on lib/page/opentreehole/quiz.dart
> +                  )
And we can let this button jump to the previous question, instead of the next.

2024-04-06 03:51 UTC, HydrogenC commented
Resolved in [a8adef6](https://github.com/DanXi-Dev/DanXi/pull/345/commits/a8adef66680fd0bc0d2243fedb000fd91526569b).

2024-04-08 13:04 UTC, HydrogenC commented
Dropped refetch and hide empty posts in response to @JingYiJun. 
Removed all magic related to scrolling and jumping.

2024-04-09 06:40 UTC, w568w requested changes
Mostly LGTM. Some minor changes needed.

2024-04-09 06:40 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "quiz_has_errors": "In the quiz, you've answered {count} questions wrong. Please press he button to redo. ",
Typo: `he` -> `the`. And there is an extra space after `.`.

2024-04-09 06:40 UTC, w568w commented on lib/page/opentreehole/hole_login.dart
> +        jumpBackIgnoringBackable();
Originally, `jumpBackIgnoringBackable` would return `false` to trigger a pop of the HoleLoginPage, e.g. tapping back button on the first page of the login wizard would pop the whole page. 

Does this change prevent user from exiting the login page?

2024-04-09 07:27 UTC, HydrogenC commented on lib/page/opentreehole/hole_login.dart
> +        jumpBackIgnoringBackable();
I'll test this out

2024-04-09 07:43 UTC, w568w requested changes

2024-04-09 07:43 UTC, w568w commented on lib/page/opentreehole/quiz.dart
> +                      TextSpan(
The user does not know how many questions he has answered and how many questions there are in total!

Consider adding a text indicator here? (e.g. `(1/15) xxxxx?`)

2024-04-09 07:44 UTC, w568w commented on lib/page/opentreehole/hole_login.dart
> +        jumpBackIgnoringBackable();
> I'll test this out

I have tested and confirmed this. Nothing happens when tapping back button on the first page of login wizard.

2024-04-09 09:55 UTC, HydrogenC commented on lib/page/opentreehole/hole_login.dart
> +        jumpBackIgnoringBackable();
I forgot that I have to pop the navigator manually, adding manual pop logic will fix.

2024-04-09 11:58 UTC, HydrogenC commented on lib/page/opentreehole/quiz.dart
> +                      TextSpan(
I will do that tonight.

2024-04-09 13:26 UTC, w568w commented on lib/util/master_detail_view.dart
> +              await navigatorKey!.currentState!.maybePop();
Is this... right? I see you just ignored `return true` in your refactoring again. Is it impossible to exit the app with back button now?

2024-04-09 13:42 UTC, HydrogenC commented on lib/util/master_detail_view.dart
> +              await navigatorKey!.currentState!.maybePop();
Is it really intended that we should exit when poping last dialog? It may lead to a lot of misoperations.

2024-04-09 13:48 UTC, HydrogenC commented on lib/util/master_detail_view.dart
> +              await navigatorKey!.currentState!.maybePop();
Anyway, I implemented the popping to desktop in the lastest commit.

2024-04-09 13:49 UTC, w568w commented on lib/util/master_detail_view.dart
> +              await navigatorKey!.currentState!.maybePop();
> Is it really intended that we should exit when poping last dialog? It may lead to a lot of misoperations. There is a better way to exit, to use the back-to-desktop shortcut.

I think it is. I checked Google Play and AOSP apps - they all exit with back button tapped.

2024-04-09 13:50 UTC, HydrogenC commented on lib/util/master_detail_view.dart
> +              await navigatorKey!.currentState!.maybePop();
Added already :)

2024-04-13 05:06 UTC, w568w commented
Sorry for being busy these days. I will review it ASAP.

2024-04-20 05:52 UTC, w568w commented
Sorry really busy these days. 

@ivanfei-1 @singularity-s0 Could you help review it? Merely some fuzzy testing is enough.

2024-05-22 03:40 UTC, w568w approved these changes
Mostly LGTM.

2024-05-22 03:40 UTC, w568w commented on lib/page/opentreehole/hole_detail.dart
> +    // Remove empty results
Could you add some comments to explain why there will be some empty results which should be removed?

2024-05-22 03:40 UTC, w568w commented on lib/page/opentreehole/hole_detail.dart
> +    allFloors.removeWhere((element) => element.content?.isEmpty ?? true);
Ditto.

2024-05-22 06:14 UTC, HydrogenC commented on lib/page/opentreehole/hole_detail.dart
> +    // Remove empty results
Related to #343. Sir Jingyijun told me that the server will send sensitive floors as empty floors, these changes ars to adapt with this "feature". We won't need these as soon as the upstream no longer sends empty floors.

2024-05-22 06:41 UTC, w568w commented on lib/page/opentreehole/hole_detail.dart
> +    // Remove empty results
> Related to #343. Sir Jingyijun told me that the server will send sensitive floors as empty floors and should be filtered out, these changes ars to adapt with this "feature". We won't need these as soon as the upstream no longer sends empty floors.

Yep. I mean, could you please add the explanation in the codes above?

2024-05-22 06:45 UTC, HydrogenC commented on lib/page/opentreehole/hole_detail.dart
> +    // Remove empty results
Update: Upstream no longer sends empty floors, so by now these lines should be removed.

2024-05-22 13:37 UTC, HydrogenC commented
Empty checking removed due to upstream updates.

2024-05-22 15:36 UTC, merged