Support syntax highlight for markdown and modify course review labels
DanXi-Dev/DanXi pull request #423
Opened 2024-09-16 04:25 UTC by HydrogenC

Resolves #386, closes #309.  
Implementation of syntax highlight is powered by `flutter_highlighting`. 

> 原 issue 中提到的 [flutter_highlight](https://pub.dev/packages/flutter_highlight) 最后更新是 2021 年，其 fork 版 [flutter_highlighting](https://pub.dev/packages/flutter_highlighting) 也已经停止维护约 10 个月。我的建议是迁移到支持代码高亮的 Markdown 库，[markdown_widget](https://pub.dev/packages/markdown_widget)。

I didn't use [markdown_widget](https://pub.dev/packages/markdown_widget) because it supports less customization settings than [flutter_markdown](https://pub.dev/packages/flutter_markdown) and thus makes switching difficult. Moreover, [markdown_widget](https://pub.dev/packages/markdown_widget) depends on [flutter_highlight](https://pub.dev/packages/flutter_highlight) for syntax highlighting, which haven't been updated for 3 years (much longer than [flutter_highlighting](https://pub.dev/packages/flutter_highlighting)).

2024-09-16 07:01 UTC, w568w requested changes
Mostly LGTM. Some minor problems.

2024-09-16 07:01 UTC, w568w commented on lib/widget/forum/render/render_impl.dart
> +              md.ExtensionSet([const md.FencedCodeBlockSyntax()], []));
What is `FencedCodeBlockSyntax` for?

2024-09-17 02:00 UTC, HydrogenC commented on lib/widget/forum/render/render_impl.dart
> +              md.ExtensionSet([const md.FencedCodeBlockSyntax()], []));
I copied them from code in the post <https://github.com/flutter/flutter/issues/81755>. However, I confirmed that is isn't required since `MarkdownWidget` adopts `githubFlavoredExtension` by default, which includes `FencedCodeBlockSyntax()`. Removed.

2024-09-17 05:35 UTC, w568w approved these changes
LGTM.

2024-09-17 05:36 UTC, merged