Implement webvpn on Android
DanXi-Dev/DanXi pull request #447
Opened 2024-11-25 14:57 UTC by HydrogenC

Closes #362. Tested on Windows.  
It works now. The only defect is that the waiting time for first load is very slow (because it waits too long for direct access). Even though I've set the timeout to 2s, it still takes ~10s for direct access attempt to fail, resulting in long loading time at first request.  
For reviewers: though I've checked already, please double-check that I have correctly set the request method of every api (I might have forgotten to change the request method after copying).  
Also fixes a bug where NullPointerEception will be raised when failed to acquire toml and the forum page turns red. Added some null checks so that this would no longer happen.

2024-11-25 15:44 UTC, HydrogenC commented
cc @kooWZ , please test if it works on Android.

2024-11-25 16:31 UTC, w568w requested changes
Great work! I've just completed some preliminary static code analysis and might conduct more in-depth testing later.

2024-11-25 16:31 UTC, w568w commented on lib/repository/base_repository.dart
> +          sendTimeout: const Duration(seconds: 2));
Any special reason of tuning these timeout values?

2024-11-25 16:31 UTC, w568w commented on lib/repository/danke/curriculum_board_repository.dart
> +        method: "PUT",
Have you considered https://github.com/DanXi-Dev/DanXi/issues/362#issuecomment-2267446801?

2024-11-25 16:31 UTC, w568w commented on lib/repository/forum/forum_repository.dart
> +        method: "PUT",
Ditto.

2024-11-25 16:31 UTC, w568w commented on lib/repository/base_repository.dart
> +      _dios[linkHost]!.interceptors.add(CookieManager(globalCookieJar));
I’m quite concerned about this change: have you considered scenarios where WebVPN is not enabled? 

If this change is correct, it would mean that the CookieJar isolation we previously implemented was completely unnecessary (this opinion clearly requires more thorough testing), and you should also remove `_cookieJars` completely.

Otherwise, if it’s incorrect, have you considered cases where cookies need to be separated? For example, `fdty.fudan.edu.cn` uses a login method different from normal UIS login, so we previously used a separate `cookieJar` to handle their login processes individually.

Additionally, I’m also concerned about codes where the "local" cookieJar is cleared arbitrarily, such as with `cookieJar.clearAllCookies()`… Anyway, I think this change will require more time for thorough testing.

2024-11-25 16:31 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +        await loginSession;
Just a comment: A cleverer solution to prevent concurrent login! 👍 

I believe I have made it too complex in `UISLoginTool`, since I am a little old-school. 😅 Maybe we should refactor that some day.

2024-11-25 16:31 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +          StateProvider.personInfo.value);
Technically, we do not allow the use of the global `StateProvider` instance outside the application layer... But well, perhaps `WebvpnProxy` could be considered part of the application layer in some sense. A more compliant solution would be to add a `PersonInfo` parameter to this function, but this might make higher-level calls to `WebvpnProxy` too complex.

2024-11-25 16:31 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +    throw WebVpnLoginException(options.method);
Can we make the exception message more self-descriptive? An `"Error: POST"` could be confusing for debugging.

2024-11-25 17:07 UTC, w568w commented
By the way, I think we might need to squash and clean up the commit history. Right now, it contains some experimental commits and merge commits. I can help with that after you've completed all the requested changes from the review.

2024-11-26 03:09 UTC, HydrogenC commented on lib/repository/danke/curriculum_board_repository.dart
> +        method: "PUT",
Handled in the inplementation of `requestWithProxy`.

2024-11-26 03:26 UTC, kooWZ commented
> cc @kooWZ , please test if it works on Android.

I will check this as soon as server maintainance is over

2024-11-26 04:09 UTC, HydrogenC commented on lib/util/webvpn_proxy.dart
> +          StateProvider.personInfo.value);
I decoupled this by adding a `_personInfo` field in the class, and the field will be initialized when loading UIS info into memory.

2024-11-26 04:12 UTC, HydrogenC commented on lib/repository/base_repository.dart
> +          sendTimeout: const Duration(seconds: 2));
To shorten the timeout for direct connect, or we'll have to wait for too long during first connect.

2024-11-26 04:17 UTC, HydrogenC commented
@w568w I created a new `ReadonlyCookieJar` and a separate side-by-side cookie manager for resolving the problem. Also, I added a field `isWebvpnApplicable` for each linkhost so that the webvpn cookie jar will only be added to dios related with forum and cirricular board. But I'm not sure if I've done this correctly, please review.

2024-11-26 04:17 UTC, HydrogenC commented on lib/repository/base_repository.dart
> +      _dios[linkHost]!.interceptors.add(CookieManager(globalCookieJar));
See comment below.

2024-11-26 04:35 UTC, w568w requested changes

2024-11-26 04:35 UTC, w568w commented on lib/page/home_page.dart
> +    WebvpnProxy.initPerson(StateProvider.personInfo.value);
`LoginDialog.showLoginDialog` does not block! So when the user hasn't logged in, you are accessing `StateProvider.personInfo.value` before it's set.

2024-11-26 04:35 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +    }
Consider adding notes for this path hacking behavior in the docstring of `requestWithProxy`?

A careless developer might use the PUT method in a repository for other websites and be confused by unexpected behavior (maybe 404 Not Found). Alternatively, maybe you might simply remove these lines and manually change all PUT requests to PATCH in Forum and Danke repository, or add a method argument to control the hacking behavior.

2024-11-26 04:35 UTC, w568w commented on lib/repository/base_repository.dart
> +      }
According to [the source](https://github.com/cfug/dio/blob/540616204d73814fd07855ef0e0a3b88424ec0a5/plugins/cookie_manager/lib/src/cookie_mgr.dart#L60-L61), if you add multiple `CookieManager`s to a dio instance, The last added `CookieManager` will always overwrite the entire `Cookie` field in the header. So it is equivalent to only adding `CookieManager(WebvpnProxy.webvpnCookieJar)`.

If you want both to make effects, you may need kind of `CookieManagerMerger`…

2024-11-26 05:19 UTC, HydrogenC commented on lib/util/webvpn_proxy.dart
> +    }
But I still have to keep PUT as-is when I'm using LAN instead of WebVPN, haven't I?

2024-11-26 05:23 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +    }
> But I still have to keep PUT as-is when I'm using LAN instead of WebVPN, haven't I?

No! Our server certainly does not stop one from using the `PATCH` variant in the LAN environment.

2024-11-26 05:37 UTC, HydrogenC commented on lib/repository/base_repository.dart
> +      }
Well, that's pretty discouraging, but I could handle this.

2024-11-26 05:38 UTC, HydrogenC commented on lib/page/home_page.dart
> +    WebvpnProxy.initPerson(StateProvider.personInfo.value);
Tricky point indeed.

2024-11-26 06:03 UTC, HydrogenC commented on lib/page/home_page.dart
> +    WebvpnProxy.initPerson(StateProvider.personInfo.value);
Resolved in [e420abf](https://github.com/DanXi-Dev/DanXi/pull/447/commits/e420abf4604ebddaf1b417aa812bc51447188f50)

2024-11-26 06:10 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +    }
> So it would be more preferrable to both use the PATCH api regardless of the connect mode?

Yes.

2024-11-26 06:38 UTC, HydrogenC commented
Resolved.

2024-11-26 06:45 UTC, w568w reviewed
Mostly LGTM! We need to go through some real-world tests before merging.

2024-11-27 02:24 UTC, w568w commented
Two problems I noticed when testing on Windows:

1. The initial request is still slow, taking ~5 seconds or more.
2. Forum images fail to load. It might be worth considering proxying image requests as well. See <https://github.com/DanXi-Dev/DanXi/blob/main/lib/util/io/cache_manager_with_proxy.dart> for inspiration.

2024-11-27 02:29 UTC, w568w requested changes
Two problems I noticed when testing on Windows:

1. The initial request is still slow, taking ~5 seconds or more. It needs to be fixed in this PR.
2. Forum images fail to load. It might be worth considering proxying image requests as well. See <https://github.com/DanXi-Dev/DanXi/blob/main/lib/util/io/cache_manager_with_proxy.dart> for inspiration. Since this requires additional work, my suggestion is to submit an issue immediately after this PR is merged to track the progress, ensuring it doesn't delay the release.

2024-11-27 03:24 UTC, HydrogenC commented
> 1. The initial request is still slow, taking ~5 seconds or more. It needs to be fixed in this PR.
The only method is to decrese the timeout when trying direct links. 
> 2. Forum images fail to load. It might be worth considering proxying image requests as well. See https://github.com/DanXi-Dev/DanXi/blob/main/lib/util/io/cache_manager_with_proxy.dart for inspiration. Since this requires additional work, my suggestion is to submit an issue immediately after this PR is merged to track the progress, ensuring it doesn't delay the release.
Why is this happening, I have already proxied IMAGE_BASE_URL. Is there any other modules that have to be changed to make it work?

2024-11-27 03:37 UTC, w568w commented
> The only method is to decrese the timeout when trying direct links.

Or, you can heuristically determine whether one is on campus:

https://github.com/DanXi-Dev/DanXi/blob/56c29c8570332ea352460d5691fdce9dc5bb7872/lib/page/subpage_dashboard.dart#L103-L111

> Is there any other modules that have to be changed to make it work?

The problem is that the `CachedNetworkImage` widget does not rely on Dio at all. It requests images through `DefaultCacheManager` that declares a `fileService`, which contains `HttpClient`. You may have to re-route that `HttpClient`. Check the file I listed above.

2024-11-27 03:58 UTC, HydrogenC commented
> > The only method is to decrese the timeout when trying direct links.
> 
> Or, you can heuristically determine whether one is on campus:

No, this approach is also slow. The off-campus notification pops up after ～5s after application launch. If the url isn't available, dio won't return before counting all the timeout. 

Sidenote: I wouldn't be able to code until tonight due to experiment courses. Sorry for high latency of resolving code reviews.

2024-11-27 08:33 UTC, HydrogenC commented
As for the first point, it now responds within 1~2 seconds.  

As for the second point, fixed and tested on windows (image below, taken under webvpn mode)
![屏幕截图 2024-11-27 163240](https://github.com/user-attachments/assets/1b250bf8-5452-4303-9e85-3d4749b9e2f6)

2024-11-27 08:36 UTC, w568w commented
dc5671a3f3b3e8e85e70b69e45d5c94bd4346c0a removes supports of #369, do I get it right?

2024-11-27 08:43 UTC, HydrogenC commented
> Edit: I am wrong. `HttpFileServiceWithWebvpn` uses `DioUtils.newDioWithProxy` to create a dio supporting HTTP proxy. Never mind.

Yeah I mentioned this in the comment of `DefaultCacheManagerWithWebvpn`.

2024-11-27 08:56 UTC, w568w approved these changes
Impressive. Will merge it as soon as I complete some testing.

2024-11-27 08:56 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +  static Future<bool>? tryDirectSession;
(This is just a comment)

I would say that the most similar thing coming to my mind is a mutex with `try_acquire`, because I will accomplish the same behavior in C/C++ with something like:

```cpp
if (lock.try_acquire()) {
    // ... do logging in ...
} else {
    lock.acquire(); // only block and wait for finishing
}
lock.release();
```

2024-11-27 09:01 UTC, HydrogenC commented on lib/util/webvpn_proxy.dart
> +  static Future<bool>? tryDirectSession;
Okay, I considered using mutex before, however it doesn't support `try_acquire` so I gave up.

2024-11-27 09:03 UTC, w568w commented on lib/util/webvpn_proxy.dart
> +  static Future<bool>? tryDirectSession;
> Okay, I considered using mutex before, however it doesn't support `try_acquire` so I gave up.

That's why I utilized a bunch of things in `UISLoginTool`: read-write lock, epoch-based task, etc. 😅

2024-11-27 09:37 UTC, w568w commented
I have tested on Android. Everything works.

2024-11-27 09:44 UTC, merged