Feat: #445, #432
DanXi-Dev/DanXi pull request #448
Opened 2024-11-26 03:21 UTC by kooWZ

Closes #445, #432
#445 is not tested since the server is under maintainance

2024-11-26 03:44 UTC, w568w requested changes
Mostly LGTM. Some minor changes.

2024-11-26 03:44 UTC, w568w commented on lib/page/subpage_timetable.dart
> +    DateTime? lastUpdatedTime = timetableLastUpdated != null ? DateTime.tryParse(timetableLastUpdated) : null;
Can you move these `DateTime <-> String` logic to SettingsProvider? The raw string stored would better not be exposed to the UI layer. `settingsProvider.timetableLastUpdated` should be a `DateTime?`.

2024-11-26 03:44 UTC, w568w commented on lib/page/subpage_timetable.dart
> +    String? timetableLastUpdated = SettingsProvider.getInstance().timetableLastUpdated;
`SettingsProvider.getInstance()` is discouraged in the UI layer, because this approach does not automatically refresh the UI when the data is updated. Could you use `context.select<SettingsProvider, String?>(...)` instead?

2024-11-27 04:16 UTC, kooWZ commented on lib/page/subpage_timetable.dart
> +    DateTime? lastUpdatedTime = timetableLastUpdated != null ? DateTime.tryParse(timetableLastUpdated) : null;
fixed

2024-11-27 04:16 UTC, kooWZ commented on lib/page/subpage_timetable.dart
> +    String? timetableLastUpdated = SettingsProvider.getInstance().timetableLastUpdated;
fixed

2024-11-27 04:32 UTC, w568w requested changes

2024-11-27 04:32 UTC, w568w commented on lib/repository/fdu/postgraduate_timetable_repository.dart
> +      SettingsProvider.getInstance().timetableLastUpdated = DateTime.now();
You do not await the result, so `timetableLastUpdated` will be updated before the timetable is fetched.

2024-11-27 04:32 UTC, w568w commented on lib/repository/fdu/time_table_repository.dart
> +      SettingsProvider.getInstance().timetableLastUpdated = DateTime.now();
Ditto.

2024-11-27 04:32 UTC, w568w commented on lib/page/forum/hole_editor.dart
> +                  Expanded(
Have you tested it? An `Expanded` inside a column with `MainAxisSize.min`… 

To be honest, I don't know what vertical constraints `PlatformModalSheet` will pass down to the column. If it pass down an unbounded constraint, an assertion will be triggered.

2024-11-27 10:13 UTC, ivanfei-1 commented on lib/repository/fdu/postgraduate_timetable_repository.dart
> +      SettingsProvider.getInstance().timetableLastUpdated = DateTime.now();
Fixed.

2024-11-27 10:13 UTC, ivanfei-1 commented on lib/repository/fdu/time_table_repository.dart
> +      SettingsProvider.getInstance().timetableLastUpdated = DateTime.now();
Fixed.

2024-11-27 11:45 UTC, kooWZ commented on lib/page/forum/hole_editor.dart
> +                  Expanded(
tested on my phone and it works

2024-11-27 12:50 UTC, w568w commented
Seems not fixed.
![image](https://github.com/user-attachments/assets/27394b1b-9852-4afc-b88e-6440f9c94b49)

2024-11-27 15:28 UTC, ivanfei-1 commented
All fixed.

2024-11-27 15:48 UTC, w568w approved these changes
LGTM.

2024-11-27 15:48 UTC, merged