feat #443: add 'show this person' function to hole
DanXi-Dev/DanXi pull request #466
Opened 2024-12-09 10:25 UTC by AInfinity-LilacDream

2024-12-09 10:28 UTC, AInfinity-LilacDream commented
this function seems to conflict with current "only show dz" function. if you consider that they should co-exist, this pr may solve the problem. or, you may delete the "only show dz" function.

2024-12-09 14:47 UTC, HydrogenC commented
Could we unify these two functions? I am saying that we could delete the legacy stuff for `Only DZ`, instead we can just set `selectedPerson=NAME OF DZ` to provide the same functionality in a unified way.

2024-12-09 14:49 UTC, w568w commented
> Could we unify these two functions? I am saying that we could delete the legacy stuff for `Only DZ`, instead we can just set `selectedPerson=NAME OF DZ` to provide the same functionality in a unified way.

+1 for this. I think it is the preferred way.

2024-12-11 08:26 UTC, w568w requested changes
LGTM. Minor changes required.

2024-12-11 08:26 UTC, w568w commented on lib/l10n/intl_en.arb
> +  "show_this_person": "Show this person"
Suggestion: change to `"This user only"`.

2024-12-11 08:26 UTC, w568w commented on lib/l10n/intl_ja.arb
> +  "show_this_person": "この人を見てください"
Suggestion: change to `"この人だけ"`.

2024-12-11 08:26 UTC, w568w commented on lib/widget/forum/forum_widgets.dart
Please revert nonsense style changes (e.g. delete/add an empty line) before submitting a PR, if possible.

2024-12-11 08:26 UTC, w568w commented on lib/page/forum/hole_detail.dart
> +  String? selectedPerson;
As `selectedPerson` can be `null`, why not simply use `selectedPerson == null` to represent the state that `onlyShowSelectedPerson = false`? So you can remove the variable `onlyShowSelectedPerson`.

2024-12-11 16:48 UTC, AInfinity-LilacDream commented on lib/page/forum/hole_detail.dart
> +  String? selectedPerson;
Sorry for the unnecessary codes.
Too noob, trying to improve my coding ability.
Wanna assign a couple of more issues in the future.

2024-12-11 17:36 UTC, w568w requested changes
You haven't dealt with *every* change request yet. Please tackle all of them before re-request the review.

2024-12-11 17:45 UTC, w568w commented on lib/page/forum/hole_detail.dart
> +  String? selectedPerson;
> Sorry for the unnecessary codes. Too noob, trying to improve my coding ability. 

Never mind! Everyone begins as a noob :)

By the way, don't panic when someone reviews your code! They are totally fine, and **the person pointing out the problem is NOT trying to criticize you (or doubt your abilities)**. We are working together solely to make the project better.

**A better PR deserves a more detailed review.** PRs with no comments are either of little value (e.g., fixing a single obvious bug or merely formatting code) or have already been re-submitted after multiple internal discussions.

2024-12-11 17:46 UTC, w568w commented on lib/page/forum/hole_detail.dart
> +  String? selectedPerson;
Also, if you resolved a change request, use `Resolve conversation` button below to close it.

2024-12-12 02:52 UTC, w568w approved these changes
LGTM!

2024-12-12 02:52 UTC, merged